### ISSUE TITLE
Add Partners Logo and link in Footer

### ISSUE THREAD

**Issue by megbutler** [BaltimoreCity/HackBaltimore#254]
Add the 9 images with links to the URLs listed to the footer. Add in same location where Code for Baltimore logo is currently shown.

HackUMBC
IMAGE: https://dl.airtable.com/.attachments/73899514d2845b8dda6690bb431fc071/a87c53fb/umbclogo.png
URL: https://www.hackumbc.org/

MedHacks
IMAGE: https://dl.airtable.com/.attachments/f829e1e49ac53422a84d47a860b16524/b6c11bbc/MedHacks.png
URL: medhacks.io

Harbor Hacks - Digital Harbor
IMAGE (choose one option): 
(1) https://dl.airtable.com/.attachments/101775a6d21f4ce9849a0c0f0f5ae892/0d707777/harborhacks.jpg
(2) https://dl.airtable.com/.attachments/9edb81763ca6df51bc731eab037dc18f/3e9717de/ScreenShot2019-01-28at6.54.50PM.png

Baltimore Hackathon
IMAGE: https://dl.airtable.com/.attachments/805f92d12a63a8ad4663dbdd27e6dd20/8c615521/HackBaltimore.jpg
URL: https://www.baltimorehackathon.com/

GiveBackHack Baltimore
IMAGE: https://dl.airtable.com/.attachments/796006a64beebf2a928c0309e9079892/d79a2c9c/GBHBaltimoreicon.png
URL: https://givebackhack.com/baltimore/

Hack for Impact Baltimore
IMAGE: https://dl.airtable.com/.attachments/e3a98b87c6b70543a8b4e8fc66bfdeaf/6ef687a7/ScreenShot2019-01-24at4.07.22PM.png
URL: https://hack-for-impact.devpost.com/

DevOpsDays
IMAGE: https://dl.airtable.com/.attachments/61aa71e2b89f3683499e44c923f65a39/4f385cd9/sponsor-DevOpsDays.png
URL: https://www.devopsdays.org/events/2019-baltimore/welcome/

Harmony Hacks: Peabody
IMAGE: https://dl.airtable.com/.attachments/5ca3474db6ba1b55be53b76fa32b07ce/7c640613/ScreenShot2019-01-28at6.25.26PM.png
URL: https://peabody.jhu.edu/explore-peabody/libraries-archives/hacking-harmony/

HopHacks
IMAGE: https://dl.airtable.com/.attachments/93cc0b535d4b0d0261c01cbc27142428/45826754/hophacks.png
URL: https://hophacks.com/

**Comment by maysam** [comment]
how should the design go? 

![image](https://user-images.githubusercontent.com/591033/56691889-38a77f80-66f6-11e9-856d-fd8ca4a04683.png)

![image](https://user-images.githubusercontent.com/591033/56691911-44934180-66f6-11e9-821e-9009d3f10cb2.png)


![image](https://user-images.githubusercontent.com/591033/56692000-6ab8e180-66f6-11e9-9ff0-9692c11b2c6f.png)

**Comment by deld** [comment]
The first option @maysam

**Comment by lsamuels-fearless** [comment]
Resolved with https://github.com/BaltimoreCity/HackBaltimore/pull/258

**Comment by maysam** [comment]
the pull request doesn't have the link to the sponsors, it was merged too quickly

**Comment by lsamuels-fearless** [comment]
Good catch. Pushed https://github.com/BaltimoreCity/HackBaltimore/pull/259 with the correct links.
