### ISSUE TITLE
Add Partners logo/link to Website

### ISSUE THREAD

**Issue by megbutler** [BaltimoreCity/HackBaltimore#260]
- [ ] Baltimore Black Techies: https://www.meetup.com/Baltimore-Black-Techies-Meetup/
- [ ] Homebase: https://www.homebase.works/
- [ ] Startup Grind: https://www.startupgrind.com
- [ ] Mindhub: https://hub.mindgrub.com/
- [ ] Tribe: tribestaffing.co
- [ ] Women Techmakers: https://www.womentechmakers.com/
- [ ] BNIA (no link)
- [ ] General Services (no link)

**Comment by maysam** [comment]
@megbutler you want me to add the above to this part?

![image](https://user-images.githubusercontent.com/591033/57974816-6620d980-79d3-11e9-8971-76c4e070352a.png)

**Comment by megbutler** [comment]
![mindhub logo](https://user-images.githubusercontent.com/28261324/57976305-9902a780-79aa-11e9-919f-f3ef8f84a0e0.png)
![general services](https://user-images.githubusercontent.com/28261324/57976306-9902a780-79aa-11e9-9c2e-eb3e47284736.png)
![bnia](https://user-images.githubusercontent.com/28261324/57976307-9902a780-79aa-11e9-8b2b-0ec4f0d2fe25.png)
![homebase](https://user-images.githubusercontent.com/28261324/57976308-9902a780-79aa-11e9-82a7-8043ebeb86ae.png)
![women techmakers](https://user-images.githubusercontent.com/28261324/57976309-9902a780-79aa-11e9-9d37-e4e3b909af7f.png)
![baltimore black techies](https://user-images.githubusercontent.com/28261324/57976310-9902a780-79aa-11e9-9f65-4f119ae67b47.png)
![startup-grind](https://user-images.githubusercontent.com/28261324/57976311-9902a780-79aa-11e9-8a74-623bda71518d.png)

**Comment by maysam** [comment]
@megbutler how about tribestaffing.co ?
