### ISSUE TITLE
Remove Sentence from "What We Do" Section

### ISSUE THREAD

**Issue by tracispacek** [BaltimoreCity/HackBaltimore#37]
Remove the line from "What We Do" section that says: "Hack Baltimore won’t just be a reimagining of previous hackathons; we’re determined to do something bigger, better, and more effective."

![screen shot 2018-11-20 at 11 18 42 am](https://user-images.githubusercontent.com/44404015/48788739-715faa80-ecb9-11e8-984b-fbf6c47f7096.png)

**Comment by yflicker** [comment]
Done
