### ISSUE TITLE
Bio Typo 

### ISSUE THREAD

**Issue by ChelseaKeene** [BaltimoreCity/HackBaltimore#38]
Typo on the word "created" in the below sentence. See corrected version below.
Sabrina Dépestre
BRAND AND MARKETING CHAIR
Sabrina Dépestre is a Haitian-American brand strategist and marketer who has created and applied a combination of marketing campaigns, events, and best practices that lead to client growth, community engagement, and retention working with organizations like Miami HEAT and lululemon.

**Comment by lsamuels-fearless** [comment]
Resolved by https://github.com/BaltimoreCity/HackBaltimore/commit/ef4343bc5cf58028dc0cb9e9b93ef66af20273ba
