### ISSUE TITLE
Update Teams with 'To Be Announced'

### ISSUE THREAD

**Issue by tracispacek** [BaltimoreCity/HackBaltimore#4]
Like here (and again, for each focus area): http://hackbaltimore.io/housing.html , http://hackbaltimore.io/education.html , http://hackbaltimore.io/transportation.html , http://hackbaltimore.io/safety.html , http://hackbaltimore.io/health.html , http://hackbaltimore.io/workforce.html

We need to communicate that teams will be announced and we do not have them yet. Perhaps only have one team box and add more as they come. 

<img width="1612" alt="screen shot 2018-10-23 at 11 19 23 am" src="https://user-images.githubusercontent.com/44404015/47371281-85fa5400-d6b5-11e8-98ea-b672a1541182.png">

@yflicker

**Comment by yflicker** [comment]
@tracispacek i think this is fixed in #31. please let @lsamuels-fearless and i know if not.
