### ISSUE TITLE
Update Our Partners to To Be Determined 

### ISSUE THREAD

**Issue by tracispacek** [BaltimoreCity/HackBaltimore#6]
Link (scroll to bottom): http://hackbaltimore.io/participate.html

We need to update and say that we are going to add more as they come. Can keep Baltimore Hackathon since they are already partnered with us, and say more are coming. 

<img width="1610" alt="screen shot 2018-10-23 at 11 45 31 am" src="https://user-images.githubusercontent.com/44404015/47375664-c01c2380-d6be-11e8-8633-452f21a5272a.png">

**Comment by deld** [comment]
Possibly a sample placeholder graphic for blank ones for now @yflicker ?
