### ISSUE TITLE
Update Communications Section with Proper Social Media

### ISSUE THREAD

**Issue by tracispacek** [BaltimoreCity/HackBaltimore#8]
All of these icons just take you to your own facebook page. Need to be updated to go to Hack Baltimore facebook, twitter, instagram, etc. Not sure when we will have these. 

<img width="504" alt="screen shot 2018-10-23 at 12 35 18 pm" src="https://user-images.githubusercontent.com/44404015/47376251-22295880-d6c0-11e8-84a9-100b5f9fd748.png">

**Comment by deld** [comment]
Here they are:

https://www.facebook.com/HackBmore

https://twitter.com/HackBaltimore

https://www.instagram.com/hackbaltimore/

Don't have linkedin or Google
